#pragma once
#ifndef RAYTRACINGWEEKEND_STB_IMG_INCLUDE_H
#define RAYTRACINGWEEKEND_STB_IMG_INCLUDE_H

#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_STATIC
#define STBI_FAILURE_USERMSG
#include "include/stb_image.h"

#endif //RAYTRACINGWEEKEND_STB_IMG_INCLUDE_H